# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
version: 2
updates:
  - package-ecosystem: "npm"  # Replace with the package manager you use (e.g., "pip", "maven", etc.)
    directory: "/"  # Root directory of your project, or a specific path to package manifests
    schedule:
      interval: "weekly"  # Check for updates weekly
